trigger:
- main  # Triggers the pipeline on commits to the main branch

pool:
  vmImage: ubuntu-latest  # Runs the pipeline on the latest Ubuntu VM

steps:
- task: NodeTool@0          # Use the NodeTool task to install Node.js
  inputs:
    versionSpec: '20.x'     # Install Node.js version 20.x
  displayName: 'Install Node.js'

- script: |                 # Run npm commands in a script step
    npm install
    npm run build
  displayName: 'npm install and build'
